# Generated by Django 4.2.7 on 2024-03-01 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Modificado', models.DateTimeField(auto_now=True)),
                ('Status', models.BooleanField(default=True)),
                ('pk_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('Nombre', models.CharField(default='', max_length=100)),
                ('direccion', models.CharField(max_length=20)),
                ('servicio', models.CharField(choices=[('Ejecutando', 'Ejecutando'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=50)),
                ('paquetes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userequipo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.BooleanField(default=False)),
                ('enviados', models.IntegerField(default=0)),
                ('recibidos', models.IntegerField(default=0)),
                ('perdidos', models.IntegerField(default=0)),
                ('maximo', models.IntegerField(default=0)),
                ('media', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='equipo.equipo')),
            ],
        ),
    ]
