# Generated by Django 4.2.7 on 2024-03-02 00:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Codigo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='Creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='Modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='pk_publica',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
