# Generated by Django 4.2.7 on 2024-03-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_test_codigo_test_creado_test_modificado_test_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='server',
            new_name='responde',
        ),
    ]
